# Generated by Django 5.0.1 on 2024-02-06 18:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Shoe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(default='', max_length=100)),
                ('name', models.CharField(default='', max_length=100)),
                ('size', models.CharField(default='', max_length=10)),
                ('color', models.CharField(default='', max_length=50)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('purchase_date', models.DateField(default='')),
                ('category', models.CharField(choices=[('S', 'Sneakers'), ('B', 'Boots'), ('F', 'Flats'), ('H', 'Heels'), ('S', 'Sandals')], default='S', max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Cleaning',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('cleaned', models.CharField(choices=[('M', 'Morning'), ('A', 'Afternoon'), ('E', 'Evening')], default='M', max_length=1)),
                ('shoe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.shoe')),
            ],
        ),
    ]
